export const MOCK_QUERY_CONFIG = [
  {
    isAuth: true,
    bizId: 'CAPITAL_MARKETS',
    key: 'institutionType',
    label: 'Institution type',
    sort: 1,
    placeholder: null,
    actionType: null,
    inputType: null,
    defaultValue: null,
    description: null,
    optionValues: [
      {
        key: 'Investors & Funds',
        label: 'Investors & Funds',
        value: 'INVESTORS_FUNDS',
        selected: null,
      },
      {
        key: 'Limited Partners',
        label: 'Limited Partners',
        value: 'LIMITED_PARTNERS',
        selected: null,
      },
      {
        key: 'Service Providers',
        label: 'Service Providers',
        value: 'SERVICE_PROVIDERS',
        selected: null,
      },
    ],
    url: null,
    optionMultiple: false,
    componentName: null,
    isDefault: true,
    isDefaultOpen: true,
    refreshSubsets: false,
    isGroup: true,
    groupType: 'BUTTON_GROUP',
    children: [
      {
        isAuth: true,
        bizId: 'CAPITAL_MARKETS',
        key: 'institutionType',
        label: 'Investors & Funds',
        sort: 1,
        placeholder: null,
        actionType: 'CLICK',
        inputType: null,
        defaultValue: 'INVESTORS_FUNDS',
        description: '',
        optionValues: null,
        url: '',
        optionMultiple: false,
        componentName: null,
        isDefault: true,
        isDefaultOpen: true,
        refreshSubsets: true,
        isGroup: true,
        groupType: null,
        children: [
          {
            isAuth: true,
            bizId: 'CAPITAL_MARKETS',
            key: 'entityType',
            label: 'Entity type',
            sort: 1,
            placeholder: null,
            actionType: null,
            inputType: null,
            defaultValue: null,
            description: null,
            optionValues: [
              { key: 'Firm', label: 'Firm', value: 'FIRM', selected: null },
              {
                key: 'Executive',
                label: 'Executive',
                value: 'EXECUTIVE',
                selected: null,
              },
            ],
            url: null,
            optionMultiple: false,
            componentName: null,
            isDefault: true,
            isDefaultOpen: true,
            refreshSubsets: false,
            isGroup: true,
            groupType: 'TAB',
            children: [
              {
                isAuth: true,
                bizId: 'CAPITAL_MARKETS',
                key: 'entityType',
                label: 'Firm',
                sort: 1,
                placeholder: null,
                actionType: 'CLICK',
                inputType: null,
                defaultValue: null,
                description: null,
                optionValues: null,
                url: null,
                optionMultiple: false,
                componentName: null,
                isDefault: true,
                isDefaultOpen: true,
                refreshSubsets: false,
                isGroup: false,
                groupType: null,
                children: [
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: null,
                    label: 'Firm profile',
                    sort: 1,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'firmType',
                        label: 'Firm type',
                        sort: 1,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'firmName',
                        label: 'Firm name',
                        sort: 2,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'aum',
                        label: 'Assets under management (AUM)',
                        sort: 3,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: [
                          {
                            key: 'Under $1M',
                            label: 'Under $1M',
                            value: '0-1',
                            selected: null,
                          },
                          {
                            key: '$1M - $5M',
                            label: '$1M - $5M',
                            value: '1-5',
                            selected: null,
                          },
                          {
                            key: '$5M - $10M',
                            label: '$5M - $10M',
                            value: '5-10',
                            selected: null,
                          },
                          {
                            key: '$10M - $50M',
                            label: '$10M - $50M',
                            value: '10-50',
                            selected: null,
                          },
                          {
                            key: '$50M - $200M',
                            label: '$50M - $200M',
                            value: '50-200',
                            selected: null,
                          },
                          {
                            key: '$200M - $1B',
                            label: '$200M - $1B',
                            value: '200-1000',
                            selected: null,
                          },
                          {
                            key: '$1B - $10B',
                            label: '$1B - $10B',
                            value: '1000-10000',
                            selected: null,
                          },
                          {
                            key: '$10B+',
                            label: '$10B+',
                            value: '10000+',
                            selected: null,
                          },
                        ],
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'investmentSector',
                        label: 'Investment sector',
                        sort: 4,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description:
                          '(Limited coverage - available for select firms only)',
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: null,
                    label: 'Location',
                    sort: 2,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'location',
                        label: '',
                        sort: 1,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: 'excludeFirms',
                    label: 'Exclude firms',
                    sort: 3,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: [
                      {
                        key: 'TABLE',
                        label: 'Existing table of firms',
                        value: 'TABLE',
                        selected: null,
                      },
                      {
                        key: 'LIST',
                        label: 'List of firm identifiers',
                        value: 'LIST',
                        selected: null,
                      },
                    ],
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: false,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'EXCLUDE_FIRMS',
                    children: null,
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: null,
                    label: 'Additional details',
                    sort: 4,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'ADDITIONAL_DETAILS',
                    children: null,
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: '',
                    label: 'Limit results',
                    sort: 5,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'limit',
                        label: '',
                        sort: 1,
                        placeholder: 'e.g. 10',
                        actionType: 'INPUT',
                        inputType: 'NUMBER',
                        defaultValue: null,
                        description: 'up to {} records per search',
                        optionValues: null,
                        url: null,
                        optionMultiple: false,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'onlyShowNewRecords',
                        label: '',
                        sort: 2,
                        placeholder: null,
                        actionType: 'CHECKBOX',
                        inputType: 'BOOLEAN',
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: false,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: 'Only show new records',
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                ],
                subLabel: null,
                tooltip: null,
              },
              {
                isAuth: true,
                bizId: 'CAPITAL_MARKETS',
                key: 'entityType',
                label: 'Executive',
                sort: 2,
                placeholder: null,
                actionType: 'CLICK',
                inputType: null,
                defaultValue: null,
                description: null,
                optionValues: null,
                url: null,
                optionMultiple: false,
                componentName: null,
                isDefault: false,
                isDefaultOpen: false,
                refreshSubsets: false,
                isGroup: false,
                groupType: null,
                children: [
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: null,
                    label: 'Firm profile',
                    sort: 1,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'firmType',
                        label: 'Firm type',
                        sort: 1,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'firmName',
                        label: 'Firm name',
                        sort: 2,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'aum',
                        label: 'Assets under management (AUM)',
                        sort: 3,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: [
                          {
                            key: 'Under $1M',
                            label: 'Under $1M',
                            value: '0-1',
                            selected: null,
                          },
                          {
                            key: '$1M - $5M',
                            label: '$1M - $5M',
                            value: '1-5',
                            selected: null,
                          },
                          {
                            key: '$5M - $10M',
                            label: '$5M - $10M',
                            value: '5-10',
                            selected: null,
                          },
                          {
                            key: '$10M - $50M',
                            label: '$10M - $50M',
                            value: '10-50',
                            selected: null,
                          },
                          {
                            key: '$50M - $200M',
                            label: '$50M - $200M',
                            value: '50-200',
                            selected: null,
                          },
                          {
                            key: '$200M - $1B',
                            label: '$200M - $1B',
                            value: '200-1000',
                            selected: null,
                          },
                          {
                            key: '$1B - $10B',
                            label: '$1B - $10B',
                            value: '1000-10000',
                            selected: null,
                          },
                          {
                            key: '$10B+',
                            label: '$10B+',
                            value: '10000+',
                            selected: null,
                          },
                        ],
                        url: null,
                        optionMultiple: false,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'investmentSector',
                        label: 'Investment sector',
                        sort: 4,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description:
                          '(Limited coverage - available for select firms only)',
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: '',
                    label: 'Title',
                    sort: 2,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'title',
                        label: '',
                        sort: 1,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: '',
                    label: 'Location',
                    sort: 3,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'executiveLocation',
                        label: 'Executive location',
                        sort: 1,
                        placeholder:
                          'Search by city, state, country, or region',
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'firmLocation',
                        label: 'Firm location',
                        sort: 2,
                        placeholder:
                          'Search by city, state, country, or region',
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: 'includeFirms',
                    label: 'Firms',
                    sort: 4,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: [
                      {
                        key: 'TABLE',
                        label: 'Existing table of firms',
                        value: 'TABLE',
                        selected: null,
                      },
                      {
                        key: 'LIST',
                        label: 'List of firm identifiers',
                        value: 'LIST',
                        selected: null,
                      },
                    ],
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: false,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'EXCLUDE_FIRMS',
                    children: null,
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: 'excludeIndividuals',
                    label: 'Exclude individuals',
                    sort: 5,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: false,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'EXCLUDE_INDIVIDUALS',
                    children: null,
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: null,
                    label: 'Additional details',
                    sort: 6,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'ADDITIONAL_DETAILS',
                    children: null,
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: '',
                    label: 'Limit results',
                    sort: 7,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'limitResults',
                        label: '',
                        sort: 1,
                        placeholder: 'e.g. 10',
                        actionType: 'INPUT',
                        inputType: 'NUMBER',
                        defaultValue: null,
                        description: 'up to {} records per search',
                        optionValues: null,
                        url: null,
                        optionMultiple: false,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'limitPerCompany',
                        label: 'Limit per company',
                        sort: 2,
                        placeholder: 'e.g. 10',
                        actionType: 'INPUT',
                        inputType: 'NUMBER',
                        defaultValue: null,
                        description:
                          'Limit the number of people shown from each company',
                        optionValues: null,
                        url: null,
                        optionMultiple: false,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                ],
                subLabel: null,
                tooltip: null,
              },
            ],
            subLabel: null,
            tooltip: null,
          },
        ],
        subLabel: null,
        tooltip: null,
      },
      {
        isAuth: true,
        bizId: 'CAPITAL_MARKETS',
        key: 'institutionType',
        label: 'Limited Partners',
        sort: 2,
        placeholder: null,
        actionType: 'CLICK',
        inputType: null,
        defaultValue: 'LIMITED_PARTNERS',
        description: '',
        optionValues: null,
        url: '',
        optionMultiple: false,
        componentName: null,
        isDefault: false,
        isDefaultOpen: false,
        refreshSubsets: true,
        isGroup: true,
        groupType: null,
        children: [
          {
            isAuth: true,
            bizId: 'CAPITAL_MARKETS',
            key: 'entityType',
            label: 'Entity type',
            sort: 1,
            placeholder: null,
            actionType: null,
            inputType: null,
            defaultValue: null,
            description: null,
            optionValues: [
              { key: 'Firm', label: 'Firm', value: 'FIRM', selected: null },
              {
                key: 'Executive',
                label: 'Executive',
                value: 'EXECUTIVE',
                selected: null,
              },
            ],
            url: null,
            optionMultiple: false,
            componentName: null,
            isDefault: true,
            isDefaultOpen: true,
            refreshSubsets: false,
            isGroup: true,
            groupType: 'TAB',
            children: [
              {
                isAuth: true,
                bizId: 'CAPITAL_MARKETS',
                key: 'entityType',
                label: 'Firm',
                sort: 1,
                placeholder: null,
                actionType: 'CLICK',
                inputType: null,
                defaultValue: null,
                description: null,
                optionValues: null,
                url: null,
                optionMultiple: false,
                componentName: null,
                isDefault: true,
                isDefaultOpen: true,
                refreshSubsets: false,
                isGroup: false,
                groupType: null,
                children: [
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: null,
                    label: 'Firm profile',
                    sort: 1,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'firmType',
                        label: 'Firm type',
                        sort: 1,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'firmName',
                        label: 'Firm name',
                        sort: 2,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'aum',
                        label: 'Assets under management (AUM)',
                        sort: 3,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: [
                          {
                            key: 'Under $1M',
                            label: 'Under $1M',
                            value: '0-1',
                            selected: null,
                          },
                          {
                            key: '$1M - $5M',
                            label: '$1M - $5M',
                            value: '1-5',
                            selected: null,
                          },
                          {
                            key: '$5M - $10M',
                            label: '$5M - $10M',
                            value: '5-10',
                            selected: null,
                          },
                          {
                            key: '$10M - $50M',
                            label: '$10M - $50M',
                            value: '10-50',
                            selected: null,
                          },
                          {
                            key: '$50M - $200M',
                            label: '$50M - $200M',
                            value: '50-200',
                            selected: null,
                          },
                          {
                            key: '$200M - $1B',
                            label: '$200M - $1B',
                            value: '200-1000',
                            selected: null,
                          },
                          {
                            key: '$1B - $10B',
                            label: '$1B - $10B',
                            value: '1000-10000',
                            selected: null,
                          },
                          {
                            key: '$10B+',
                            label: '$10B+',
                            value: '10000+',
                            selected: null,
                          },
                        ],
                        url: null,
                        optionMultiple: false,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'mandate',
                        label: 'Mandate',
                        sort: 4,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description:
                          '(Limited coverage - available for select firms only)',
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: null,
                    label: 'Location',
                    sort: 2,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'location',
                        label: '',
                        sort: 1,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: 'excludeFirms',
                    label: 'Exclude firms',
                    sort: 3,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: [
                      {
                        key: 'TABLE',
                        label: 'Existing table of firms',
                        value: 'TABLE',
                        selected: null,
                      },
                      {
                        key: 'LIST',
                        label: 'List of firm identifiers',
                        value: 'LIST',
                        selected: null,
                      },
                    ],
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: false,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'EXCLUDE_FIRMS',
                    children: null,
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: null,
                    label: 'Additional details',
                    sort: 4,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'ADDITIONAL_DETAILS',
                    children: null,
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: '',
                    label: 'Limit results',
                    sort: 5,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'limitResults',
                        label: '',
                        sort: 1,
                        placeholder: 'e.g. 10',
                        actionType: 'INPUT',
                        inputType: 'NUMBER',
                        defaultValue: null,
                        description: 'up to {} records per search',
                        optionValues: null,
                        url: null,
                        optionMultiple: false,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                ],
                subLabel: null,
                tooltip: null,
              },
              {
                isAuth: true,
                bizId: 'CAPITAL_MARKETS',
                key: 'entityType',
                label: 'Executive',
                sort: 2,
                placeholder: null,
                actionType: 'CLICK',
                inputType: null,
                defaultValue: null,
                description: null,
                optionValues: null,
                url: null,
                optionMultiple: false,
                componentName: null,
                isDefault: false,
                isDefaultOpen: false,
                refreshSubsets: false,
                isGroup: false,
                groupType: null,
                children: [
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: '',
                    label: 'High-Net-Worth Individuals',
                    sort: 1,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'isHnw',
                        label: 'Show High Net Worth clients only',
                        sort: 1,
                        placeholder: null,
                        actionType: 'SWITCH',
                        inputType: null,
                        defaultValue: null,
                        description:
                          'High-net-worth clients are individuals with significant financial assets, usually over $1 million in investable wealth',
                        optionValues: null,
                        url: null,
                        optionMultiple: false,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: null,
                    label: 'Firm profile',
                    sort: 2,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'firmType',
                        label: 'Firm type',
                        sort: 1,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'firmName',
                        label: 'Firm name',
                        sort: 2,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'aum',
                        label: 'Assets under management (AUM)',
                        sort: 3,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: [
                          {
                            key: 'Under $1M',
                            label: 'Under $1M',
                            value: '0-1',
                            selected: null,
                          },
                          {
                            key: '$1M - $5M',
                            label: '$1M - $5M',
                            value: '1-5',
                            selected: null,
                          },
                          {
                            key: '$5M - $10M',
                            label: '$5M - $10M',
                            value: '5-10',
                            selected: null,
                          },
                          {
                            key: '$10M - $50M',
                            label: '$10M - $50M',
                            value: '10-50',
                            selected: null,
                          },
                          {
                            key: '$50M - $200M',
                            label: '$50M - $200M',
                            value: '50-200',
                            selected: null,
                          },
                          {
                            key: '$200M - $1B',
                            label: '$200M - $1B',
                            value: '200-1000',
                            selected: null,
                          },
                          {
                            key: '$1B - $10B',
                            label: '$1B - $10B',
                            value: '1000-10000',
                            selected: null,
                          },
                          {
                            key: '$10B+',
                            label: '$10B+',
                            value: '10000+',
                            selected: null,
                          },
                        ],
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'mandate',
                        label: 'Mandate',
                        sort: 4,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description:
                          '(Limited coverage - available for select firms only)',
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: '',
                    label: 'Title',
                    sort: 3,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'title',
                        label: '',
                        sort: 1,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: '',
                    label: 'Location',
                    sort: 4,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'executiveLocation',
                        label: 'Executive location',
                        sort: 1,
                        placeholder:
                          'Search by city, state, country, or region',
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'firmLocation',
                        label: 'Firm location',
                        sort: 2,
                        placeholder:
                          'Search by city, state, country, or region',
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: 'includeFirms',
                    label: 'Firms',
                    sort: 5,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: [
                      {
                        key: 'TABLE',
                        label: 'Existing table of firms',
                        value: 'TABLE',
                        selected: null,
                      },
                      {
                        key: 'LIST',
                        label: 'List of firm identifiers',
                        value: 'LIST',
                        selected: null,
                      },
                    ],
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: false,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'EXCLUDE_FIRMS',
                    children: null,
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: '',
                    label: 'Exclude individuals',
                    sort: 6,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: false,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'EXCLUDE_INDIVIDUALS',
                    children: null,
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: null,
                    label: 'Additional details',
                    sort: 7,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'ADDITIONAL_DETAILS',
                    children: null,
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: '',
                    label: 'Limit results',
                    sort: 8,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'limitResults',
                        label: '',
                        sort: 1,
                        placeholder: 'e.g. 10',
                        actionType: 'INPUT',
                        inputType: 'NUMBER',
                        defaultValue: null,
                        description: 'up to {} records per search',
                        optionValues: null,
                        url: null,
                        optionMultiple: false,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: [
                          {
                            isAuth: true,
                            bizId: 'CAPITAL_MARKETS',
                            key: 'limitPerCompany',
                            label: 'Limit per company',
                            sort: 2,
                            placeholder: 'e.g. 10',
                            actionType: 'INPUT',
                            inputType: 'NUMBER',
                            defaultValue: null,
                            description:
                              'Limit the number of people shown from each company',
                            optionValues: null,
                            url: null,
                            optionMultiple: false,
                            componentName: null,
                            isDefault: true,
                            isDefaultOpen: true,
                            refreshSubsets: false,
                            isGroup: false,
                            groupType: null,
                            children: null,
                            subLabel: null,
                            tooltip: null,
                          },
                        ],
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'limitResultsCompany',
                        label: 'Limit per company',
                        sort: 2,
                        placeholder: 'e.g. 10',
                        actionType: 'INPUT',
                        inputType: 'NUMBER',
                        defaultValue: null,
                        description:
                          'Limit the number of people shown from each company',
                        optionValues: null,
                        url: null,
                        optionMultiple: false,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                ],
                subLabel: null,
                tooltip: null,
              },
            ],
            subLabel: null,
            tooltip: null,
          },
        ],
        subLabel: null,
        tooltip: null,
      },
      {
        isAuth: true,
        bizId: 'CAPITAL_MARKETS',
        key: 'institutionType',
        label: 'Service Providers',
        sort: 3,
        placeholder: null,
        actionType: 'CLICK',
        inputType: null,
        defaultValue: 'SERVICE_PROVIDERS',
        description: '',
        optionValues: null,
        url: '',
        optionMultiple: false,
        componentName: null,
        isDefault: false,
        isDefaultOpen: false,
        refreshSubsets: true,
        isGroup: true,
        groupType: null,
        children: [
          {
            isAuth: true,
            bizId: 'CAPITAL_MARKETS',
            key: 'entityType',
            label: 'Entity type',
            sort: 1,
            placeholder: null,
            actionType: null,
            inputType: null,
            defaultValue: null,
            description: null,
            optionValues: [
              { key: 'Firm', label: 'Firm', value: 'FIRM', selected: null },
              {
                key: 'Executive',
                label: 'Executive',
                value: 'EXECUTIVE',
                selected: null,
              },
            ],
            url: null,
            optionMultiple: false,
            componentName: null,
            isDefault: true,
            isDefaultOpen: true,
            refreshSubsets: false,
            isGroup: true,
            groupType: 'TAB',
            children: [
              {
                isAuth: true,
                bizId: 'CAPITAL_MARKETS',
                key: 'entityType',
                label: 'Firm',
                sort: 1,
                placeholder: null,
                actionType: 'CLICK',
                inputType: null,
                defaultValue: null,
                description: null,
                optionValues: null,
                url: null,
                optionMultiple: false,
                componentName: null,
                isDefault: true,
                isDefaultOpen: true,
                refreshSubsets: false,
                isGroup: false,
                groupType: null,
                children: [
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: null,
                    label: 'Firm profile',
                    sort: 1,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'firmType',
                        label: 'Firm type',
                        sort: 1,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'firmName',
                        label: 'Firm name',
                        sort: 2,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: null,
                    label: 'Location',
                    sort: 2,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'location',
                        label: '',
                        sort: 1,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: 'excludeFirms',
                    label: 'Exclude firms',
                    sort: 3,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: [
                      {
                        key: 'TABLE',
                        label: 'Existing table of firms',
                        value: 'TABLE',
                        selected: null,
                      },
                      {
                        key: 'LIST',
                        label: 'List of firm identifiers',
                        value: 'LIST',
                        selected: null,
                      },
                    ],
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: false,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'EXCLUDE_FIRMS',
                    children: null,
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: null,
                    label: 'Additional details',
                    sort: 4,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'ADDITIONAL_DETAILS',
                    children: null,
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: '',
                    label: 'Limit results',
                    sort: 5,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'limitResults',
                        label: '',
                        sort: 1,
                        placeholder: 'e.g. 10',
                        actionType: 'INPUT',
                        inputType: 'NUMBER',
                        defaultValue: null,
                        description: 'up to {} records per search',
                        optionValues: null,
                        url: null,
                        optionMultiple: false,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                ],
                subLabel: null,
                tooltip: null,
              },
              {
                isAuth: true,
                bizId: 'CAPITAL_MARKETS',
                key: 'entityType',
                label: 'Executive',
                sort: 2,
                placeholder: null,
                actionType: 'CLICK',
                inputType: null,
                defaultValue: null,
                description: null,
                optionValues: null,
                url: null,
                optionMultiple: false,
                componentName: null,
                isDefault: false,
                isDefaultOpen: false,
                refreshSubsets: false,
                isGroup: false,
                groupType: null,
                children: [
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: null,
                    label: 'Firm profile',
                    sort: 1,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'firmType',
                        label: 'Firm type',
                        sort: 1,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'firmName',
                        label: 'Firm name',
                        sort: 2,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: false,
                        isDefaultOpen: false,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: '',
                    label: 'Title',
                    sort: 2,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'title',
                        label: '',
                        sort: 1,
                        placeholder: null,
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: '',
                    label: 'Location',
                    sort: 3,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'executiveLocation',
                        label: 'Executive location',
                        sort: 1,
                        placeholder:
                          'Search by city, state, country, or region',
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'firmLocation',
                        label: 'Firm location',
                        sort: 2,
                        placeholder:
                          'Search by city, state, country, or region',
                        actionType: 'SELECT',
                        inputType: null,
                        defaultValue: null,
                        description: null,
                        optionValues: null,
                        url: null,
                        optionMultiple: true,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: 'includeFirms',
                    label: 'Firms',
                    sort: 4,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: [
                      {
                        key: 'TABLE',
                        label: 'Existing table of firms',
                        value: 'TABLE',
                        selected: null,
                      },
                      {
                        key: 'LIST',
                        label: 'List of firm identifiers',
                        value: 'LIST',
                        selected: null,
                      },
                    ],
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: false,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'EXCLUDE_FIRMS',
                    children: null,
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: '',
                    label: 'Exclude individuals',
                    sort: 5,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: false,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'EXCLUDE_INDIVIDUALS',
                    children: null,
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: null,
                    label: 'Additional details',
                    sort: 6,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'ADDITIONAL_DETAILS',
                    children: null,
                    subLabel: null,
                    tooltip: null,
                  },
                  {
                    isAuth: true,
                    bizId: 'CAPITAL_MARKETS',
                    key: '',
                    label: 'Limit results',
                    sort: 8,
                    placeholder: null,
                    actionType: null,
                    inputType: null,
                    defaultValue: null,
                    description: null,
                    optionValues: null,
                    url: null,
                    optionMultiple: false,
                    componentName: null,
                    isDefault: true,
                    isDefaultOpen: true,
                    refreshSubsets: false,
                    isGroup: true,
                    groupType: 'GENERAL',
                    children: [
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'limit',
                        label: '',
                        sort: 1,
                        placeholder: 'e.g. 10',
                        actionType: 'INPUT',
                        inputType: 'NUMBER',
                        defaultValue: null,
                        description: 'up to {} records per search',
                        optionValues: null,
                        url: null,
                        optionMultiple: false,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                      {
                        isAuth: true,
                        bizId: 'CAPITAL_MARKETS',
                        key: 'limitPerCompany',
                        label: 'Limit per company',
                        sort: 2,
                        placeholder: 'e.g. 10',
                        actionType: 'INPUT',
                        inputType: 'NUMBER',
                        defaultValue: null,
                        description:
                          'Limit the number of people shown from each company',
                        optionValues: null,
                        url: null,
                        optionMultiple: false,
                        componentName: null,
                        isDefault: true,
                        isDefaultOpen: true,
                        refreshSubsets: false,
                        isGroup: false,
                        groupType: null,
                        children: null,
                        subLabel: null,
                        tooltip: null,
                      },
                    ],
                    subLabel: null,
                    tooltip: null,
                  },
                ],
                subLabel: null,
                tooltip: null,
              },
            ],
            subLabel: null,
            tooltip: null,
          },
        ],
        subLabel: null,
        tooltip: null,
      },
    ],
    subLabel: null,
    tooltip: null,
  },
];
