import { TableFilterConditionType } from '@/types';

export const CONDITION_LABEL_MAP: Record<string, string> = {
  [TableFilterConditionType.equal_to]: 'equal to',
  [TableFilterConditionType.not_equal_to]: 'not equal to',
  [TableFilterConditionType.contains]: 'contains',
  [TableFilterConditionType.contains_any_of]: 'contains any of',
  [TableFilterConditionType.does_not_contain]: 'does not contain',
  [TableFilterConditionType.does_not_contain_any_of]: 'does not contain any of',
  [TableFilterConditionType.is_empty]: 'is empty',
  [TableFilterConditionType.is_not_empty]: 'is not empty',
  [TableFilterConditionType.greater_than]: 'greater than',
  [TableFilterConditionType.greater_or_equal_to]: 'greater or equal to',
  [TableFilterConditionType.less_than]: 'less than',
  [TableFilterConditionType.less_or_equal_to]: 'less or equal to',
  [TableFilterConditionType.is_between]: 'is between',
  [TableFilterConditionType.is_checked]: 'is checked',
  [TableFilterConditionType.is_not_checked]: 'is not checked',
  [TableFilterConditionType.is]: 'is',
  [TableFilterConditionType.is_not]: 'is not',
  [TableFilterConditionType.has_an_error]: 'has an error',
  [TableFilterConditionType.does_not_contain_an_error]:
    'does not contain an error',
  [TableFilterConditionType.has_results]: 'has results',
  [TableFilterConditionType.has_no_results]: 'has no results',
  [TableFilterConditionType.has_not_run]: 'has not run',
  [TableFilterConditionType.is_queued]: 'is queued',
  [TableFilterConditionType.is_awaiting_callback]: 'is awaiting callback',
  [TableFilterConditionType.is_retrying]: 'is retrying',
  [TableFilterConditionType.run_condition_not_met]: 'run condition not met',
  [TableFilterConditionType.is_running]: 'is running',
  [TableFilterConditionType.is_not_running]: 'is not running',
  [TableFilterConditionType.is_stale]: 'is stale',
};
